apiVerion: v1
kind: Namespace
metadata: 
  name: mysql-secret
  namespace: PetLove
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: petlove
  MYSQL_USER: aluno
  MYSQL_PASSWORD: senha123